# tmux設定ファイル

# prefixキーをC-bからC-qに変更
unbind C-b
set -g prefix C-q
bind C-q send-prefix

# ウィンドウとペインのインデックスを1から始める
set -g base-index 1
setw -g pane-base-index 1

# マウス操作を有効化
set -g mouse on

# ウィンドウ分割のキーバインド
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# ペインサイズ調整
bind-key -n M-Up resize-pane -U 3
bind-key -n M-Down resize-pane -D 3
bind-key -n M-Left resize-pane -L 3
bind-key -n M-Right resize-pane -R 3

# ペイン移動のキーバインド（vim風）
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# ペインリサイズのキーバインド
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# 設定ファイルのリロード
bind-key r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# ステータスバーの設定
set -g status-position top
set -g status-interval 1


# メッセージの設定
set -g message-style fg=colour232,bg=colour166,bold

# カラー設定
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# escapeキーの遅延を解消
set -sg escape-time 0

# ヒストリの上限
set -g history-limit 10000

# プラグインの設定
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-pain-control'

## catppuccin config
set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_middle_separator " "
set -g @catppuccin_window_right_separator_inverse "yes"
set -g @catppuccin_window_right_separator "█"
set -g @catppuccin_window_number_position "left"
set -g @catppuccin_window_default_fill "none"
set -g @catppuccin_window_current_fill "all"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_directory_color "yellow"
set -g @catppuccin_status_modules_right "directory application"
set -g @catppuccin_status_modules_left "session"
set -g @catppuccin_status_left_separator  "█"
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_right_separator_inverse "yes"
set -g @catppuccin_status_fill "all"
set -g @catppuccin_status_connect_separator "no"

## コピーモードのキーバインド設定 vi 
setw -g mode-keys vi

## Start selection with 'v'
bind -T copy-mode-vi v send-keys -X begin-selection

## Copy to clipboard with 'y'
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"


# プラグインマネージャーの初期化
run '~/.tmux/plugins/tpm/tpm'