#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Gyazo 退会ウィザード（cap.so へ移行）
# 値の保存は行わない。人間にしかできない操作（解約・アカウント削除）を案内し、
# アプリ削除だけ確認のうえ brew で実行する。
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

# gyazo.com がメンテナンス中だと設定ページも 404 になり、解約・削除ができない。
# Web 操作を伴うステージの前に呼び、メンテ中なら「後で再実行」を案内して終了する。
require_gyazo_up() {
  local body
  body=$(curl -s -m 10 -A 'Mozilla/5.0' https://gyazo.com/ 2>/dev/null || true)
  if [[ -z "$body" ]] || grep -qi 'under maintenance' <<<"$body"; then
    warn "gyazo.com が応答しないかメンテナンス中です。設定ページには入れません。"
    note "しばらく待ってから、このウィザードをもう一度実行してください（値は保存しないので最初からで問題ありません）。"
    exit 1
  fi
}

banner "Gyazo 退会（cap.so へ移行）"
require_gyazo_up

# ── Stage 1: Gyazo Pro の解約（契約している場合のみ）────────────────────
stage "Gyazo Pro の解約"
say "Pro を契約したままだとアカウント削除ができないので、先に無料プランへ戻します。"
if confirm "Gyazo Pro（または Teams）を契約していますか?"; then
  open_url "https://gyazo.com/settings"
  step "設定ページのメニューから「決済情報」を開く。"
  step "「プラン変更」ボタンを押してダウングレードページへ進む。"
  step "「無料プランを選択」を押して完了する。"
  note "支払い済み期間の満了までは Pro が使え、期限後に自動で無料プランになります。返金はありません。"
  warn "Teams の管理者なら、先に Teams 側の解約ページで解約してください。"
  pause "無料プランへの変更が完了したら Enter"
else
  note "無料プランなので解約手続きは不要です。"
  pause "Enter で次へ"
fi

# ── Stage 2: アカウント削除 ───────────────────────────────────────────
stage "Gyazo アカウントの削除"
warn "削除するとアップロード済みの画像・動画もすべてサーバーから消えます（復元不可）。"
say "残したい画像があれば、先にダウンロードしてから進んでください。"
require_gyazo_up
open_url "https://gyazo.com/settings"
step "設定ページの一番下までスクロールし「アカウントを削除する」を押す。"
step "確認ダイアログで削除を承認する。"
note "画像が多い場合は削除処理に時間がかかることがあります。"
if confirm "アカウントの削除を実行しましたか?"; then
  note "アカウント削除を確認しました。"
else
  SKIPPED+=("Gyazo アカウントの削除（https://gyazo.com/settings の末尾「アカウントを削除する」）")
  warn "後で手動で削除してください。"
fi

# ── Stage 3: macOS アプリの削除 ───────────────────────────────────────
stage "Gyazo アプリのアンインストール"
say "gyazo cask は flake.nix から外してあり、switch 時の cleanup=uninstall で消えているはずです。残っていればここで削除します。"
step "メニューバーの Gyazo / Gyazo GIF を終了する（アイコンをクリック → Quit）。"
pause "終了したら Enter"
if command -v brew >/dev/null 2>&1 && brew list --cask gyazo >/dev/null 2>&1; then
  if confirm "brew uninstall --cask --zap gyazo を実行しますか?（設定ファイルも削除）"; then
    brew uninstall --cask --zap gyazo && printf '  %s✓ 削除しました%s Gyazo.app\n' "$GREEN" "$RESET"
  else
    SKIPPED+=("Gyazo アプリの削除: brew uninstall --cask --zap gyazo")
  fi
else
  note "gyazo cask は見つかりませんでした。Gyazo.app が残っていれば手動でゴミ箱へ。"
fi
step "システム設定 → プライバシーとセキュリティ → 画面収録 に Gyazo が残っていれば外す。"
pause "確認したら Enter"

finish
